DATASET:
  DATA_ROOT: /home/zhanghaokui/data/nas_data
  DATA_NAME: DIV2K_800
#TEST_DATASETS: [Set5, Set14, BSD100, Urban100, Manga109]
  TEST_DATASETS: [Set5, Set14, BSD100, Urban100, Manga109]
  CROP_SIZE: 64
  TASK: "sr"
  TO_GRAY: False
SEARCH:
  TIE_CELL: False
DATALOADER:
  BATCH_SIZE_TEST: 32
  S_FACTOR: 4
MODEL:
  FILTER_MULTIPLIER: 16
  META_ARCHITECTURE: Sr_compnet
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 2
  NUM_BLOCKS: 3
  IN_CHANNEL: 3
  PRIMITIVES: "NO_DEF_L"
  ACTIVATION_F: "Leaky"
  USE_ASPP: True
  USE_RES: True

OUTPUT_DIR: output

