DATASET:
  DATA_ROOT: /home/zhanghaokui/data/nas_data
  # DATA_ROOT: /data/data2/zhk218/data/nas_data
  DATA_NAME: DIV2K_800
  CROP_SIZE: 64
  TASK: "sr"
  LOAD_ALL: False
SEARCH:
  TIE_CELL: False
INPUT:
  CROP_SIZE_TRAIN: 64
SOLVER:
  TRAIN:
    MAX_ITER: 600000
  CHECKPOINT_PERIOD: 1000
  VALIDATE_PERIOD: 1000
  LOSS: ['l1', 'log_ssim']
  LOSS_WEIGHT: [1.0, 0.6]
DATALOADER:
  NUM_WORKERS: 4
  BATCH_SIZE_TRAIN: 16
  BATCH_SIZE_TEST: 16
  S_FACTOR: 8
  R_CROP: 4
MODEL:
  FILTER_MULTIPLIER: 16
  META_ARCHITECTURE: Sr_compnet
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 2
  NUM_BLOCKS: 3
  IN_CHANNEL: 3
  PRIMITIVES: "NO_DEF_L"
  ACTIVATION_F: "Leaky"
  USE_ASPP: True
  USE_RES: True

OUTPUT_DIR: output

