DATASET:
  DATA_ROOT: /home/ren/hkzhang/data_p/nas_data
  DATA_NAME: BSD500_300
  CROP_SIZE: 64
  TASK: "dn"
  LOAD_ALL: True
  TO_GRAY: True
SEARCH:
  TIE_CELL: False
INPUT:
  CROP_SIZE_TRAIN: 64  
SOLVER:
  TRAIN:
   MAX_ITER: 600000
  CHECKPOINT_PERIOD: 1000  
  VALIDATE_PERIOD: 1000
  LOSS: ['mse', 'log_ssim']
  LOSS_WEIGHT: [1.0, 0.6]
DATALOADER:
  NUM_WORKERS: 2
  BATCH_SIZE_TRAIN: 24
  BATCH_SIZE_TEST: 24
  SIGMA: [30]
  DATA_AUG: 5
MODEL:
  FILTER_MULTIPLIER: 20
  META_ARCHITECTURE: Dn_compnet
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 3
  NUM_BLOCKS: 4
  IN_CHANNEL: 1
  PRIMITIVES: "NO_DEF_L"
  ACTIVATION_F: "Leaky"
  USE_ASPP: False
  USE_RES: True

OUTPUT_DIR: output_R0

