DATASET:
  DATA_ROOT: /home/ren/hkzhang/data_p/nas_data
  DATA_NAME: BSD500_300
  CROP_SIZE: 64
  TASK: "dn"
  LOAD_ALL: True
  TO_GRAY: True
SEARCH:
  SEARCH_ON: True
  ARCH_START_EPOCH: 20
  TIE_CELL: False
  R_SEED: 20
MODEL:
  META_ARCHITECTURE: Dn_supernet
  META_MODE: Width
  NUM_STRIDES: 3
  NUM_LAYERS: 3
  NUM_BLOCKS: 4
  FILTER_MULTIPLIER: 10
  IN_CHANNEL: 1
  PRIMITIVES: "NO_DEF_L"
  ACTIVATION_F: "Leaky"
  AFFINE: False
  USE_ASPP: False
  USE_RES: True
DATALOADER:
  BATCH_SIZE_TRAIN: 6
  BATCH_SIZE_TEST: 12
  NUM_WORKERS: 4
  SIGMA: [30, 50, 70]
  DATA_LIST_DIR: ../preprocess/dataset_json

SOLVER:
  LOSS: ['mse', 'log_ssim']
  LOSS_WEIGHT: [1.0, 0.5]
  MAX_EPOCH: 100

OUTPUT_DIR: output_R20
